name = "HybridElectric"
uuid = "c96e3844-487f-4050-bdd3-dbe48e83499a"
version = "0.1.0"
authors = ["Sabinaaaaaaaaaa <sabinamh03@gmail.com>"]


[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
